spring.application.name=fashionithm

# Server
server.port=8080

# Logging
logging.level.com.example.fashionithm=DEBUG

# Encoding
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
